### ISSUE TITLE
Impossible to notarize

### ISSUE THREAD

**Issue by protee** [miyako/4d-plugin-midi#3]
Hi Miyako, 
the plugin works now with v18 and Catalina, and it is perfect.
But I'm not able to Notarize my App, the error comes from this plugin.
As you can see, timidity is the problem.
Can you do something? Do you need more explainantion?

    {LogFile}
            logFormatVersion 1
            jobId d7174f06-0688-43dc-ae72-eb95cb4e8f7f
            status Invalid
            statusSummary Archive contains critical validation errors
            statusCode 4000
            archiveFilename Oviyam_v2.zip
            uploadDate 2021-04-27T18:47:08Z
            sha256 dacd5552517c0aaa9808548a10d96c756496ebfecc25393982787da7560e1b6c
            ticketContents 
            [issues: 1]
                     issues [1]
                        severity error
                        code 
                        path Oviyam_v2.zip/Oviyam v2.app/Contents/Plugins/midi.bundle/Contents/MacOS/timidity
                        message The executable does not have the hardened runtime enabled.
                        docUrl 
                        architecture x86_64

**Comment by miyako** [comment]
the post-build code signing script needs to be updated to sign the tmidity program with hardened runtime and the plugin without.

for now, the tmidity source project does not seem to support apple silicon, not a blocking problem for the plugin, though it would be nice if the whole set could be ARM native.

**Comment by protee** [comment]
Thank you, do you know how to do what you suggest? I mean update tmidity with hardened runtime only?

**Comment by miyako** [comment]
please use release [2.1.0](https://github.com/miyako/4d-plugin-midi/releases/tag/2.1.0)

**Comment by protee** [comment]
Ok, Miyako, I found the issue. I'll explain on the 4D forum as it is of general interest !
The problem resides in "4d-utility-build-application-master", as with the 4D signing, it is ok, and with your signing, MIDI fails...

**Comment by miyako** [comment]
that makes sense, the tool does not know that an executable exists next to the plugin. I guess you can comment out the code that erases existing code signature.

**Comment by protee** [comment]
Yes, but 4D signing in v18 is able to manage it automatically. So I ask myself on how to manage it in your signing method !

**Comment by miyako** [comment]
4D signing doe not remove existing signature. that is the difference.

**Comment by miyako** [comment]
in line #65 or thereabouts of `TEST` there is

```4d
//first, clean all (--remove-signature and xattr -rc)
codesign ($path;$signingIdentity;$plist;$entitlements;$remove)
```

just skip it

**Comment by protee** [comment]
I'll try it, thanks Miyako !

**Comment by protee** [comment]
Same issue Miyako.

**Comment by miyako** [comment]
did you start with a fresh copy? if you have already destroyed the signature, skipping the code means nothing.

**Comment by protee** [comment]
I'll double-check again today.

Cordialement,
______________________________
Olivier Grimbert - Protée sarl, 31 rue Sainte-Marthe 31000 Toulouse
• tél : +33(0) 970 465646 • mob : +33(0) 6 3718 5941 • skype : info-protee - www.protee.org

**Comment by protee** [comment]
I tried again, nop.
When I build in 4D v18, I have my apple certificate indicated, so 4D sign.
Then I launch your signing method, where I removed the line you said, all seems ok.
Then I create a zip, same with your method, then I try to notarize. The result is:
                     path Oviyam_v2.zip/Oviyam v2.app/Contents/Plugins/midi.bundle/Contents/MacOS/timidity
                     message The executable does not have the hardened runtime enabled.
If I just sign with 4D, and miss your signing method, the notarize is ok.
I need to resign because I want to include next a web folder, so no other option than sign again with your method, after the 4D build. Do you think the double sign is the problem?

**Comment by protee** [comment]
A) Check
I build with 4D without signing. Then I checked with Terminal if it is signed : not. Then I signed with your method without clear, and I checked again : NOT Notarized!
Terminal : 
$command:="codesign --verify --verbose "+xbuild_escape_param ($applicationPathObject.name+$applicationPathObject.extension)

B) Check
I build with 4D without signing. Then I checked with Terminal if it is signed : NOT Signed. Then I signed with your method with clear, and I checked again : Signed! 
I tried to Notarize : NOT Notarized, even Signed.

C) Check
I build with 4D with Signing. Then I checked with Terminal if it is signed : Signed. Then I sign with your method without clear, result is NOT Signed ! Then I sign with you method with clear, result Signed !!!! But if I go on Notarizing, NOK.

Hum, I'm totally stuck on this laborious process.

4D knows how to Sign properly in order to get Noterized after, even with the MIDI plugin.
But with your method, even Terminal says Signed, the Notarizing is wrong. Grrrrrrr What a lost of time for us, little developers.

**Comment by miyako** [comment]
I think it might be better to stop looking at it as a "which tool to use" problem.

Whether you use 4D or whether you write your own shell script or if you use my tool is irrelevant. they are all essentially doing the same thing.

It is really important to understand how notarisation works and design a strategy that works for you. what is correct depends on the application design, so there is no universal formula that can work for every situation.

**Comment by protee** [comment]
Ok, I'll stop disturbing you, but one thing I don't agree is 4D works well, and seems more universal than your methods, but don't miss understand me : your tool helped me a LOT to reach where I am now, definitively.
I asked 4D to add some key in the build xml file, in order to copy things in between the build process - like web folder. Then the issue won't be relevant anymore !
Thanks again

**Comment by miyako** [comment]
one more thing, there should be a flag that lets you decide whether to sign plugins or not. since the plugin is already notarised, you might want to deactivate that flag. remember, most plugins were not notarised when I published the tool.

the whole point of the component is that it gives you fine control over such details. the default settings are generally useful but you can change them according to your needs. to describe it as less universal seems a bit unfair.
